# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a91bfea8755508a704ddd128242a4015b60054c20f0ee5e2eaddb91baced68cc9e043e06ecfd10169d2b477e161ea399a5853f3368f207c77c3fb0da4cdd46f6

test:
  secret_key_base: 237b3977e2aa4314f898aa23ac76b1f44ed93bd61ff1fcf20aa914c4003fe94fb0209d10534a69a08fb5264e4ea62cb19a25672c201c283502a5f660c1910b3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
